image: debian:latest

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - npm install
    - npm run test